In [5]:
import numpy as np
a = np.ones((2,2,3));
print np.sum(a, axis=1)
np.reshape(a,(1,12))

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [7]:
import tensorflow as tf
tf.InteractiveSession()
a = tf.ones((2,2,3))
print tf.reduce_sum(a, reduction_indices=1).eval()
tf.reshape(a, (1,12)).eval()

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [13]:
import tensorflow as tf
a_constant = tf.ones((2,2))
a_variable = tf.Variable(tf.zeros((2,2)), name="weights")
with tf.Session() as sess:
    print(sess.run(a_constant))
    sess.run(tf.global_variables_initializer())
    print(sess.run(a_variable))

[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]]


In [16]:
import tensorflow as tf
c = tf.Variable(0, name="counter")
new_c = tf.add(c, tf.constant(1))
update = tf.assign(c, new_c)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print 'Start: ',
    print(sess.run(c))
    for _ in range(10):
        sess.run(update)
        print 'Loop: ',
        print(sess.run(c))

Start:  0
Loop:  1
Loop:  2
Loop:  3
Loop:  4
Loop:  5
Loop:  6
Loop:  7
Loop:  8
Loop:  9
Loop:  10


In [20]:
import numpy as np
import tensorflow as tf
a = np.zeros((3,3))
a[1,2] = 2
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[ 0.  0.  0.]
 [ 0.  0.  2.]
 [ 0.  0.  0.]]


In [26]:
import numpy as np
import tensorflow as tf
a = np.zeros((1)); a = 10
b = np.zeros((1)); b = 33
ta = tf.placeholder(tf.float32)
tb = tf.placeholder(tf.float32)
output = tf.multiply(ta, tb)
with tf.Session() as sess:
    print sess.run(output, feed_dict={ta:a, tb:b})

330.0


In [31]:
import numpy as np
import tensorflow as tf
with tf.variable_scope("foo", reuse=False):
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])
assert v.name == "foo/bar/v:0"

ValueError: Variable foo/bar/v already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<ipython-input-27-84742c720ea6>", line 5, in <module>
    v = tf.get_variable("v", [1])
  File "/Users/faisal/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/faisal/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
