In [2]:
import numpy as np

# np.linspace

In [5]:
x = np.linspace(0,1,10)
print x

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


# np.meshgrid

In [7]:
x = [-1,0,1]
y = [-4,-3,-2]
xv, yv = np.meshgrid(x,y)
print 'xv=', xv
print 'yv=', yv

xv= [[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
yv= [[-4 -4 -4]
 [-3 -3 -3]
 [-2 -2 -2]]


# np.ravel

In [12]:
m = [[1,2,3],[4,5,6],[7,8,9]]

print 'C order', np.ravel(m, order='C')
print 'F order', np.ravel(m, order='F')
print 'A order', np.ravel(m, order='A')
print 'K order', np.ravel(m, order='K')

C order [1 2 3 4 5 6 7 8 9]
F order [1 4 7 2 5 8 3 6 9]
A order [1 2 3 4 5 6 7 8 9]
K order [1 2 3 4 5 6 7 8 9]


Using np.meshgrid with np.ravel to create a grid

In [21]:
X_grid = np.array([np.ravel(xv), np.ravel(yv)])
print X_grid
print 'X_grid.shape', X_grid.shape

[[-1  0  1 -1  0  1 -1  0  1]
 [-4 -4 -4 -3 -3 -3 -2 -2 -2]]
X_grid.shape (2, 9)
